Fix first-launch-after-install issue (both platforms)
chemerisuk/cordova-plugin-firebase-dynamiclinks pull request #97
Opened 2021-07-16 19:28 UTC by ForsHant

[Pull request 96](https://github.com/chemerisuk/cordova-plugin-firebase-dynamiclinks/pull/96)

See #96 regarding PR full info.

This pull request is both an Android and iOS implementation of @misterwell solution therefore full fix PR.

2021-07-18 13:48 UTC, ForsHant commented
@chemerisuk merged with master

2021-07-18 17:10 UTC, chemerisuk requested changes

2021-07-18 17:10 UTC, chemerisuk commented on src/android/FirebaseDynamicLinksPlugin.java
> +			if (data.getLink().equals("")){
Let's rewrite and simplify this block:
```java
if ("".equals(data.getLink())) return null;
```

2021-07-18 17:13 UTC, chemerisuk commented
@ForsHant take a look at my code suggestion. Also please move this check before line 90

2021-07-21 01:08 UTC, ForsHant commented
@chemerisuk Nice suggestion. Added it :)

2021-07-21 05:14 UTC, merged

2021-07-21 05:15 UTC, chemerisuk commented
@ForsHant 👍